// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { main } from '../models';

export function ConnectToSerialPort(arg1: string, arg2: number): Promise<main.ConnectionResult>;

export function DisconnectFromSerialPort(): Promise<main.ConnectionResult>;

export function GetSerialPorts(): Promise<Array<main.SerialPortInfo>>;

export function Greet(arg1: string): Promise<string>;

export function IsConnected(): Promise<boolean>;

export function ReadSensorData(): Promise<Array<main.SensorData>>;
