// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToSerialPort(arg1, arg2) {
  return window['go']['main']['App']['ConnectToSerialPort'](arg1, arg2);
}

export function DisconnectFromSerialPort() {
  return window['go']['main']['App']['DisconnectFromSerialPort']();
}

export function GetSerialPorts() {
  return window['go']['main']['App']['GetSerialPorts']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ReadSensorData() {
  return window['go']['main']['App']['ReadSensorData']();
}
